accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    url(r'signup/', views.SignUpView.as_view(template_name = 'accounts/signup.html'), name= 'signup_url'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name= 'login_url'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name = 'accounts/logout.html'), name= 'logout_url'),

################## Password Change URL ##################
    url(r'^password_change/$', auth_views.PasswordChangeView.as_view(template_name = 'accounts/password_change.html'), name= 'password_change_url'),
    url(r'^password_change/done/$', auth_views.PasswordChangeDoneView.as_view(template_name = 'accounts/password_change_done.html'), name= 'password_change_done_url'),

################## Password Reset URL ###################
    url(r'^password_reset/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset.html'),
                                                name='password_reset_url'),
    url(r'^password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_done.html'),
                                                name='password_reset_done_url'),
    url(r'^reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'accounts/password_reset_confirm.html'),
                                                name='password_reset_confirm_url'),
    url(r'^reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = 'accounts/password_reset_complete.html'), 
                                                name='password_reset_complete_url'),
]

light/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name='index'),
    url(r'accounts/', include('accounts.urls', namespace='accounts')),
    url(r'accounts/', include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):
    phone_no = models.CharField(max_length=50, default=True)

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core import validators

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    phone_no = forms.CharField(max_length=50)
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username', 'email','phone_no', 'first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Your User Name'
    
    def clean_email(self):
        print('Total Form Validation by using single clean method...')
        # total_cleaned_data=super().clean()
        email = self.cleaned_data.get('email')
        try:
            match = User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        
        raise forms.ValidationError('This email address is already in use.')
    
        

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms

# Create your views here.
class SignUpView(CreateView):
    form_class = forms.UserRegisterForm
    success_url = reverse_lazy('login')
    template = 'accounts/signup.html'

light/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'index.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<div class="container col-md-8">
    
    <form method="POST" style="border: 1px solid black; margin: 4%; padding:6%; border-radius:1%;">
      {% csrf_token %}
      <fieldset class="form-group">
        {{ form|crispy}}
      </fieldset>
     <center>
      <button style="background: black; font-size: 1.5rem; padding:0.5%;" class="btn btn-outline-info" type="submit">Login</button>
    </center>
    <br/>
    <sub style="text-align: left;"><a href="{% url 'accounts:password_reset_url' %}" style="text-decoration: none; color: blue; padding:2%; cursor:pointer; margin-right:2%;">forget password</a></sub>
    <sub style="text-align: left;"><a href="{% url 'accounts:signup_url' %}" style="text-decoration: none; color: blue; padding:2%; cursor:pointer; margin-right:2%;">don't have account,sign up</a></sub>
    
</form>
   </div>

<!-- <div class="container">
    <div class="cotent-section">
        <form method="POST">
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    <h2>LogIn</h2>
                </legend>
                {% csrf_token %}
                {{ form|crispy }}
            </fieldset>

            <div class="form-group">
                <button class="btn btn-outline-info">Login</button>
            </div>

            <small class="text-muted">
                <a class="ml-0" href="{% url 'accounts:password_reset_url' %}">Forget Password</a>
               </small>
        </form>
    </div>
</div> -->

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<div class="container mt-3">
    <h2>You have been logged out</h2>
    </div>

{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container">
    <h1>Change Password</h1>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-primary" value="Change Password">
    </form>
</div>

{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% block body %}
<div class="alert alert-info">Password changed Successfully.</div>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %} 
<div class="container">
    <div class="cotent-section">
<form method="POST"> 
<fieldset class="form-group">
    <legend class="border-bottom mb-4"> <h2>Reset Password</h2></legend>
    {% csrf_token %}
{{ form|crispy }}
</fieldset>
<div class="form-group">
<button class="btn btn-primary">Request Password Reset</button>
</div>
</form>
</div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <p>Your password has been set. You may go ahead and login now.</p>
</div>
<hr>
<a class="btn btn-success float-right" href="{% url 'accounts:login_url' %}">Login</a>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %} 
<div class="container">
    <div class="cotent-section">
<form method="POST"> 
<fieldset class="form-group">
    <legend class="border-bottom mb-4"> <h2>Reset Password</h2></legend>
    {% csrf_token %}
{{ form|crispy }}
</fieldset>
<div class="form-group">
<button class="btn btn-success">Reset Password</button>
</div>
</form>
</div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body %}
<div class="alert alert-info">An email has been sent with instruction to reset the password.</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

        


    {% block body %}
    
    <div class="container col-md-8">
        <form method="POST" style="border: 1px solid black; margin: 4%; padding:6%; border-radius:1%;">
          {% csrf_token %}
          <fieldset class="form-group">
            {{ form|crispy}}
          </fieldset>
          <center>
            <button style="background: black; padding:1%; font-size: 1.5rem; color:white;" class="btn btn-outline-info" type="submit">Sign Up</button>
          </center>
          <br />
          <sub><a href="{% url 'accounts:login_url' %}" style="text-decoration: none; color: blue; padding:3%; cursor:pointer;">Already have an account ?</a></sub>
        </form>
    </div>
    <!-- <div class="container">
        <h1>Signup</h1>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-primary" value="Signup">
            <a type="submit" class="btn btn-primary" href="{% url 'accounts:login_url' %}">signup</a>
        </form>
    </div> -->
 
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Light</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.12.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        
        {% block customer_css %}
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
        {% endblock %}
        

    </head>
    <body>
            <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="{% url 'index' %}">Light</a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu<i class="fas fa-bars ml-1"></i></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#team">Team</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
                        {% if user.is_authenticated %}
                        <!-- <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'accounts:logout_url' %}">Logout</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'accounts:password_change_url' %}">Change Password</a></li> -->
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Welcome {{ user.username }}
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a class="dropdown-item" href="{% url 'accounts:logout_url' %}">Logout</a>
                              <a class="dropdown-item" href="#">blog</a>
                              <a class="dropdown-item" href="{% url 'accounts:password_change_url' %}">Change Password</a>
                            </div>
                          </div>
                        {% else %}
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'accounts:login_url' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'accounts:signup_url' %}">SignUp</a></li>
                        {% endif %}
                        
                        <!-- Dropdown -->

                        <!-- <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Welcome {{ user.username }}
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a class="dropdown-item" href="{% url 'accounts:logout_url' %}">Action</a>
                              <a class="dropdown-item" href="#">blog</a>
                              <a class="dropdown-item" href="{% url 'accounts:password_change_url' %}">Change Password</a>
                            </div>
                          </div> -->
                        
                    </ul>
                </div>
            </div>
        </nav>
{% block body %}
<h1> light base </h1>
{% endblock %}
        <!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-left">Copyright © Your Website 2020</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a><a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a><a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-right"><a class="mr-3" href="#!">Privacy Policy</a><a href="#!">Terms of Use</a></div>
                </div>
            </div>
        </footer>
         <!-- Bootstrap core JS-->
         <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
         <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
         <!-- Third party plugin JS-->
         <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
         <!-- Contact form JS-->
         <script src="{% static 'assets/mail/jqBootstrapValidation.js' %}"></script>
         <script src="{% static 'assets/mail/contact_me.js' %}"></script>
         <!-- Core theme JS-->
         <script src="{% static 'js/scripts.js' %}"></script>
    </body>
    </html>